services:
    web:
        build: .
        container_name: node
        ports:
            - '8080:8000'
        volumes:
            - .:/app
            - /app/node_modules
        working_dir: /app
        command: npm start
